language: rust
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev
before_script:
  - rustc -v
  - cargo -V
script:
  - cargo build -v
  - (cd src/sdl_mixer && cargo build -v)
  - (cd src/sdl_image && cargo build -v)
  - (cd src/sdl-demo && cargo build -v)
